### PR TITLE
feat: Splash screen

### PR DESCRIPTION
**Pull request by sdsantos**

### CODE REVIEW

**Review by gnarea — CHANGES_REQUESTED** [review]
Looks good on Android 8 but broken on Android 5:

Screenshot_2020-10-12-14-37-45

**Comment by sdsantos** [comment]
I can't reproduce the Android 5 issue... Is your phone screen ok? 😅
What device did you test it on?

**Comment by gnarea** [comment]
I'm using a Nexus 4 (Android 5.1) and the screen is absolutely fine. I can reproduce it consistently. Which device are you using?

I don't know if this is limited to this device. I checked [the last Firebase Test Lab run on Android 5](https://console.firebase.google.com/u/0/project/relaynet-gateway-android/testlab/histories/bh.fce322cdd2254629/matrices/8252047475986484323/executions/bs.a7b229bfd8a4ffe2/videos) but we don't have any UI tests yet, so I couldn't see the splash screen.

**Comment by sdsantos** [comment]
> I'm using a Nexus 4 (Android 5.1) and the screen is absolutely fine. I can reproduce it consistently. Which device are you using?
> 
> I don't know if this is limited to this device. I checked [the last Firebase Test Lab run on Android 5](https://console.firebase.google.com/u/0/project/relaynet-gateway-android/testlab/histories/bh.fce322cdd2254629/matrices/8252047475986484323/executions/bs.a7b229bfd8a4ffe2/videos) but we don't have any UI tests yet, so I couldn't see the splash screen.

I'm using the Nexus 5X emulator with Android 5.

**Review by gnarea — APPROVED** [review]

**Pull request merged**
