### PR TITLE
feat: UI Settings

### PR DESCRIPTION
**Pull request by sdsantos**

### CODE REVIEW

**Review by gnarea — CHANGES_REQUESTED** [review]
Did this work when you tested it?

I'm not sure if I'm doing something wrong, but the parcels sent to the courier aren't marked as in-transit and looking that the logs that's because the gateway didn't get the ACK from the courier:

```
2020-10-13 11:13:43.724 9477-9512/tech.relaycorp.gateway I/rgoMessageSetWithExpiry: Generating cargo for https://cogrpc-test.relaycorp.tech
2020-10-13 11:13:44.108 9477-10684/tech.relaycorp.gateway I/CogRPCClient: deliverCargo next 59a3bfa5-158b-49b2-ae2e-68d44c3bfe2e
2020-10-13 11:13:44.110 9477-10684/tech.relaycorp.gateway I/CogRPCClient: deliverCargo complete
2020-10-13 11:13:44.347 9477-11116/tech.relaycorp.gateway I/CogRPCClient: deliverCargo ack closed
2020-10-13 11:13:44.349 9477-11116/tech.relaycorp.gateway I/CogRPCClient: deliverCargo server did not acknowledge all cargo deliveries
2020-10-13 11:13:44.366 9477-10684/tech.relaycorp.gateway I/CogRPCClient: Closing CogRPCClient
```

But the courier appears to have sent the ACK according to its logs:

```
10-13 11:14:25.663 10451-10451/tech.relaycorp.courier I/StandaloneCoroutine: collectCargo completed empty
10-13 11:14:29.349 10451-10451/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo next 59a3bfa5-158b-49b2-ae2e-68d44c3bfe2e
10-13 11:14:29.349 10451-10629/tech.relaycorp.courier I/nService$deliverCargo$1: deliverCargo complete
```

**Comment by sdsantos** [comment]
> Did this work when you tested it?
> 
> I'm not sure if I'm doing something wrong, but the parcels sent to the courier aren't marked as in-transit and looking that the logs that's because the gateway didn't get the ACK from the courier:
> 
> ```
> 2020-10-13 11:13:43.724 9477-9512/tech.relaycorp.gateway I/rgoMessageSetWithExpiry: Generating cargo for https://cogrpc-test.relaycorp.tech
> 2020-10-13 11:13:44.108 9477-10684/tech.relaycorp.gateway I/CogRPCClient: deliverCargo next 59a3bfa5-158b-49b2-ae2e-68d44c3bfe2e
> 2020-10-13 11:13:44.110 9477-10684/tech.relaycorp.gateway I/CogRPCClient: deliverCargo complete
> 2020-10-13 11:13:44.347 9477-11116/tech.relaycorp.gateway I/CogRPCClient: deliverCargo ack closed
> 2020-10-13 11:13:44.349 9477-11116/tech.relaycorp.gateway I/CogRPCClient: deliverCargo server did not acknowledge all cargo deliveries
> 2020-10-13 11:13:44.366 9477-10684/tech.relaycorp.gateway I/CogRPCClient: Closing CogRPCClient
> ```
> 
> But the courier appears to have sent the ACK according to its logs:
> 
> ```
> 10-13 11:14:25.663 10451-10451/tech.relaycorp.courier I/StandaloneCoroutine: collectCargo completed empty
> 10-13 11:14:29.349 10451-10451/tech.relaycorp.courier I/StandaloneCoroutine: deliverCargo next 59a3bfa5-158b-49b2-ae2e-68d44c3bfe2e
> 10-13 11:14:29.349 10451-10629/tech.relaycorp.courier I/nService$deliverCargo$1: deliverCargo complete
> ```

That's weird. When closing without error it should still work. But let me change that code to move the set out of the try/catch, it shouldn't be conditional.

But that's a bug we should investigate, can you open an issue for it?

**Review by gnarea — APPROVED** [review]
I've just created https://github.com/relaycorp/relaynet-gateway-android/issues/159. Can you please look into it when you get a chance?

I'm approving this PR in the meantime.

**Comment by sdsantos** [comment]
Rebased and made this the only Settings PR.

**Review by gnarea — APPROVED** [review]

**Pull request merged**
